package ae.gov.scad.employeesdo.app;

import ae.gov.scad.employeesdo.app.common.ServiceApp;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Aug 08 23:35:27 GST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ServiceAppImpl extends ApplicationModuleImpl implements ServiceApp {
    /**
     * This is the default constructor (do not remove).
     */
    public ServiceAppImpl() {
    }

    /**
     * Container's getter for EmpROVO.
     * @return EmpROVO
     */
    public ViewObjectImpl getEmpROVO() {
        return (ViewObjectImpl) findViewObject("EmpROVO");
    }

    /**
     * Container's getter for EmpVO.
     * @return EmpVO
     */
    public ViewObjectImpl getEmpVO() {
        return (ViewObjectImpl) findViewObject("EmpVO");
    }
    
    
    
    public void print(){
        System.out.println("test sdo if it access this method ");
        }
}

