package ae.gov.scad.employeesdo.app.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Aug 08 23:39:37 GST 2020
// ---------------------------------------------------------------------
public interface ServiceApp extends ApplicationModule {
    void print();
}

