<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://packtpub.com/bpel/travel/"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                exclude-result-prefixes="oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref"
                xmlns:ns2="http://packtpub.com/service/employee/" xmlns:ns1="http://packtpub.com/service/airline/"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/TravelApprovalWrapper.wsdl"/>
        <oracle-xsl-mapper:rootElement name="TravelApproval" namespace="http://packtpub.com/bpel/travel/"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/TravelApprovalWrapper.wsdl"/>
        <oracle-xsl-mapper:rootElement name="TravelApproval" namespace="http://packtpub.com/bpel/travel/"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE JUL 14 19:54:43 GST 2020].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <ns0:TravelApproval>
      <xsl:if test="/ns0:TravelApproval/employee">
        <employee>
          <xsl:if test="/ns0:TravelApproval/employee/FirstName">
            <FirstName>
              <xsl:value-of select="/ns0:TravelApproval/employee/FirstName"/>
            </FirstName>
          </xsl:if>
          <xsl:if test="/ns0:TravelApproval/employee/LastName">
            <LastName>
              <xsl:value-of select="/ns0:TravelApproval/employee/LastName"/>
            </LastName>
          </xsl:if>
          <xsl:if test="/ns0:TravelApproval/employee/Department">
            <Department>
              <xsl:value-of select="/ns0:TravelApproval/employee/Department"/>
            </Department>
          </xsl:if>
        </employee>
      </xsl:if>
      <xsl:if test="/ns0:TravelApproval/flightData">
        <flightData>
          <xsl:if test="/ns0:TravelApproval/flightData/RequestNo">
            <RequestNo>
              <xsl:value-of select="/ns0:TravelApproval/flightData/RequestNo"/>
            </RequestNo>
          </xsl:if>
          <xsl:if test="/ns0:TravelApproval/flightData/OriginFrom">
            <OriginFrom>
              <xsl:value-of select="/ns0:TravelApproval/flightData/OriginFrom"/>
            </OriginFrom>
          </xsl:if>
          <xsl:if test="/ns0:TravelApproval/flightData/DestinationTo">
            <DestinationTo>
              <xsl:value-of select="/ns0:TravelApproval/flightData/DestinationTo"/>
            </DestinationTo>
          </xsl:if>
          <xsl:if test="/ns0:TravelApproval/flightData/DesiredDepartureDate">
            <DesiredDepartureDate>
              <xsl:value-of select="/ns0:TravelApproval/flightData/DesiredDepartureDate"/>
            </DesiredDepartureDate>
          </xsl:if>
          <xsl:if test="/ns0:TravelApproval/flightData/DesiredReturnDate">
            <DesiredReturnDate>
              <xsl:value-of select="/ns0:TravelApproval/flightData/DesiredReturnDate"/>
            </DesiredReturnDate>
          </xsl:if>
        </flightData>
      </xsl:if>
      <xsl:if test="/ns0:TravelApproval/mail">
        <mail>
          <ns0:Address>
            <xsl:value-of select="/ns0:TravelApproval/mail/ns0:Address"/>
          </ns0:Address>
        </mail>
      </xsl:if>
    </ns0:TravelApproval>
  </xsl:template>
</xsl:stylesheet>
