<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://packtpub.com/service/employee/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:ns1="http://packtpub.com/service/employee/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="EmployeeTravelStatusPT_PLT">
        <plnk:role name="EmployeeTravelStatusPT_Role" portType="ns1:EmployeeTravelStatusPT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://packtpub.com/service/employee/" location="http://127.0.0.1:7001/EmployeeTravelStatus/EmployeeTravelStatusPTPort?WSDL"/>
</wsdl:definitions>
