<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://packtpub.com/bpel/travel/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://packtpub.com/bpel/travel/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="TravelApproval">
        <plnk:role name="TravelApprovalPT" portType="tns:TravelApprovalPT"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://packtpub.com/bpel/travel/" location="TravelApproval.wsdl"/>
</wsdl:definitions>
